FROM node:21.5.0-alpine3.18
WORKDIR /app
COPY ./package.json .
COPY ./server ./server/
COPY ./shared ./shared/
RUN ["npm", "install"]
WORKDIR /app/shared/db
ENV DATABASE_URL=postgres://avnadmin:AVNS_nN7dA9HiDpeItCZmkkZ@pg-1f88603a-letsgoforitanik-8f52.a.aivencloud.com:20093/defaultdb?sslmode=require&sslcert=ca.pem
RUN ["npx", "prisma", "migrate", "dev", "--name", "init"]
WORKDIR /app/server
RUN ["npm", "run", "build"]
CMD ["npm", "run", "prod"]

